# Generated by Django 4.0.2 on 2022-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleelements',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
