# Generated by Django 4.0.2 on 2022-03-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_article_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='tag_name',
        ),
    ]
