# Generated by Django 4.0.2 on 2022-03-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_category_options_remove_category_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_insight',
            field=models.CharField(default='A', max_length=64),
            preserve_default=False,
        ),
    ]
