# Generated by Django 4.0.2 on 2022-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_article_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(default='1', max_length=8),
        ),
        migrations.AlterField(
            model_name='articleelements',
            name='type',
            field=models.CharField(choices=[('SH', 'sub_heading'), ('TX', 'textfield'), ('TW', 'twitter_embed'), ('IM', 'image_field'), ('QT', 'quote')], default='TX', max_length=2),
        ),
        migrations.AlterField(
            model_name='tagsall',
            name='tag_name',
            field=models.CharField(default='a', max_length=64),
        ),
    ]
