# Generated by Django 4.0.2 on 2022-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_article_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('jinja_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='articleelements',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
