# Generated by Django 4.0.2 on 2022-03-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_elementtype_alter_articleelements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleelements',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_type', to='article.elementtype'),
        ),
    ]
