# Generated by Django 4.0.2 on 2022-03-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_articleelements_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='submenu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category', to='article.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
