# Generated by Django 4.0.2 on 2022-03-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_category_submenu_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
