# Generated by Django 4.0.2 on 2022-03-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_sub_category', to='article.subcategory'),
        ),
    ]
