# Generated by Django 4.0.2 on 2022-03-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_regions_article_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name_plural': 'Regions'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='region',
            new_name='article_region',
        ),
    ]
