# Generated by Django 4.0.2 on 2022-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_regions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
