# Generated by Django 4.0.2 on 2022-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_article_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image_credit',
            field=models.CharField(default='A', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_insight',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.CharField(max_length=250),
        ),
    ]
