# Generated by Django 4.0.2 on 2022-03-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_article_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_insight',
            field=models.CharField(max_length=100),
        ),
    ]
