# Generated by Django 4.0.2 on 2022-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_article_article_image_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_insight',
            field=models.CharField(max_length=250),
        ),
    ]
