# Generated by Django 4.0.2 on 2022-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_article_article_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleelements',
            name='article_element_content_image_credit',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleelements',
            name='article_element_content_image_desc',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
