# Generated by Django 4.0.2 on 2022-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_articleelements_article_element_content_image_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_credit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
